import { defineConfig } from 'orval';

export default defineConfig({
  'dtm-database-backend': {
    input: './../../../openapi.json',
    output: {
      target: './lib/api/backend.ts',
      client: 'swr',
      clean: ['./lib/api'],
      override: {
        header: (info: { title?: string; version?: string }): string[] => [
          'eslint-disable @typescript-eslint/explicit-function-return-type -- This file is outmatically generated by orval',
          `Generated by orval 🍺`,
          `Do not edit manually.`,
          ...(info.title ? [info.title] : []),
          ...(info.version ? [`OpenAPI spec version: ${info.version}`] : []),
        ],
      },
    },
    hooks: {
      afterAllFilesWrite: [
        'prettier --write lib/api/backend.ts',
        'eslint --fix lib/api/backend.ts',
      ],
    },
  },
});
